import { useEffect, useState } from "react";
import BitlioLink from "../pillars/custom/BitlioLink.component";
import windowReady from "../../scripts/dom/windowReady.script";
import { UserAuth } from "../../context/AuthContext.context";
import { useRouter } from "next/router";

const DashboardSidebar = ({ user }) => {
  const [collapsed, setCollapsed] = useState(false);
  const [current, setCurrent] = useState("");

  const router = useRouter();

  useEffect(() => {
    windowReady().then((window) => {
      setCurrent(window.location.pathname);
    });
  }, []);

  const { signOutUser } = UserAuth();

  return (
    <>
      <div
        id="dashboard-sidebar"
        style={{
          width: collapsed ? "80px" : "350px",
          padding: collapsed ? "10px" : "30px",
        }}
        className={collapsed ? "text-center" : ""}
      >
        {collapsed ? (
          <span className="fs-4">
            <button
              onClick={() => setCollapsed(false)}
              className="collapse-button cursor-pointer"
              id="collapse-button-open"
            >
              <i className="fa-solid fa-bars"></i>
            </button>
          </span>
        ) : (
          <span className="text-end fs-4">
            <button
              onClick={() => setCollapsed(true)}
              className="collapse-button cursor-pointer"
              id="collapse-button-close"
            >
              <i className="fa-solid fa-xmark"></i>
            </button>
          </span>
        )}
        <BitlioLink className="text-center" href="/">
          <img
            id={
              collapsed
                ? "dashboard-sidebar-brand-logo-collapsed"
                : "dashboard-sidebar-brand-logo"
            }
            src={
              collapsed
                ? "/brand/single-white-logo.png"
                : "/brand/texted-white-logo.png"
            }
          />
          {user.type === "tutor" ? (
            <>
              {collapsed ? (
                <></>
              ) : (
                <sup className="fs-3">
                  <i className="fa-solid fa-graduation-cap"></i>
                </sup>
              )}
            </>
          ) : (
            <></>
          )}
        </BitlioLink>
        <div id="dashboard-sidebar-links">
          {[
            {
              title: "Panel",
              icon: "fa-solid fa-gauge",
              ref: "/dashboard",
            },
            {
              title: "Məqalələr",
              icon: "fa-solid fa-align-left",
              ref: "/dashboard/posts",
            },
            {
              title: "Təlimlər",
              icon: "fa-solid fa-person-chalkboard",
              ref: "/dashboard/trainings",
            },
          ].map((link, i) => (
            <div
              key={i}
              className={
                "d-flex gap-2 fs-5 dashboard-sidebar-element " +
                (current === link.ref
                  ? " dashboard-sidebar-element-active"
                  : "") +
                (collapsed ? " m-auto" : "")
              }
            >
              <BitlioLink href={link.ref}>
                <i
                  className={link.icon}
                  style={{
                    width: "30px",
                  }}
                ></i>{" "}
                {collapsed ? <></> : <>{link.title}</>}
              </BitlioLink>
            </div>
          ))}
        </div>
        <div
          id="dashboard-sidebar-profile"
          className="align-items-center"
          style={{
            marginLeft: collapsed ? "12.5px" : "",
          }}
        >
          {collapsed ? (
            <></>
          ) : (
            <>
              <span>
                <img
                  id="dashboard-sidebar-profile-user-profile-picture"
                  src={user.picture}
                />
              </span>
              <span>{user.username}</span>
            </>
          )}
          <span>
            <button
              id="sign-out-button"
              className={"cursor-pointer " + (collapsed ? "fs-4" : "")}
              onClick={() => {
                const signOutStatus = signOutUser();
                if (signOutStatus) {
                  router.push("/");
                }
              }}
            >
              <i className="fa-solid fa-door-open"></i>
            </button>
          </span>
        </div>
        {collapsed ? (
          <></>
        ) : (
          <div className="text-center">
            Generated by{" "}
            <BitlioLink
              className="text-decoration-underline fw-bold"
              href="https://bitlio.app"
            >
              Bitlio
            </BitlioLink>
          </div>
        )}
      </div>

      <style jsx>{`
        #dashboard-sidebar {
          display: flex;
          flex-direction: column;
          gap: 30px;
          padding: 30px;
        }

        #dashboard-sidebar-brand-logo {
          width: 150px;
        }

        #dashboard-sidebar-brand-logo-collapsed {
          width: 50px;
          border-radius: 5px;
        }

        #sign-out-button {
          all: unset;
          font-size: 20px;
        }

        .collapse-button {
          all: unset;
          color: #fbfbfb;
        }

        #dashboard-sidebar-profile {
          display: flex;
          gap: 10px;
          margin-top: 42vh;
        }

        #dashboard-sidebar-links {
          display: flex;
          flex-direction: column;
          gap: 5px;
        }

        #dashboard-sidebar-profile-user-profile-picture {
          width: 32px;
          height: 32px;
          border-radius: 5px;
        }

        .dashboard-sidebar-element {
          padding: 10px;
        }

        .dashboard-sidebar-element:hover {
          background: #fbfbfb;
          color: #9d81bb;
          border-radius: 10px;
        }

        .dashboard-sidebar-element-active {
          background: #fbfbfb;
          color: #9d81bb;
          border-radius: 10px;
        }
      `}</style>
    </>
  );
};

export default DashboardSidebar;
