const WatermarkPayenet = ({classes}) => {
    return (
        <div className={`text-secondary ${classes}`}>
            Generated by <span className="fw-bold">Payenet</span> (internal app of <span className="fw-bold">Bitlio</span>)
        </div>
    )
}

export default WatermarkPayenet; 